extend-exclude = [
  "archive/",
  "data/",
  "data_processor/data/",
  "project_packer/",
  "Golf_GUI/Simscape Multibody Data Plotters/Python Version/",
  "Golf_GUI/Motion Capture Plotter/",
  "Golf Swing Model/Scripts/Machine_Learning_GUI/",
  "matlab/",
  "Modern Robotics Homework/Example Projects/",
  "Modern Robotics Homework/NWU-Modern-Robotics-Capstone-Project-main/",
  "Modern Robotics Homework/Test_Scripts/",
  "Modern Robotics Homework/Python Version /",
]
